---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-0b889075aef6619b0c92fc06fcebd59c
  name: wego-test-app-9mkvk6kn
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/my-test-org-23/wego-test-app-9mkvk6kn.git
